language: c++
sanitizer:
  - address
fuzzing_engines:
  - libfuzzer
main_repo: '.'
base_os_version: ubuntu-22-04
architectures:
  - x86_64
fuzz_targets:
  - name: BatchFuzzer
    path: legacy-cpp/fuzz/batch_fuzzer.cc
  - name: RouterFuzzer
    path: legacy-cpp/fuzz/router_fuzzer.cc
  - name: SessionFuzzer
    path: legacy-cpp/fuzz/session_fuzzer.cc
  - name: FixFuzzer
    path: legacy-cpp/fuzz/fix_fuzzer.cc
  - name: SwiftFuzzer
    path: legacy-cpp/fuzz/swift_fuzzer.cc
